libs-$(CONFIG_DYMATIC_CPUFREQ) += cpu/frequence.o
libs-$(CONFIG_LOONGSON2E) += cpu/loongson2e/
libs-$(CONFIG_LOONGSON2F) += cpu/loongson2f/memcpy.o
libs-$(CONFIG_LOONGSON2G) += cpu/loongson2g/
libs-y += cpu/delay.o cpu/get-count.o 


