drivers-y += drivers/uart/uart.o drivers/flash/flash.o \
		drivers/rtc/cs5536-rtc.o drivers/cs5536/cs5536_pci.o \
		drivers/cs5536/msr.o
drivers-$(CONFIG_DYMATIC_CPUFREQ) += drivers/cs5536/mfgpt.o
drivers-$(CONFIG_SST) += drivers/flash/sst_flash.o
drivers-$(CONFIG_MACRONIX) += drivers/flash/mx_flash.o 

